environment: prod
securityContext:
  runAsNonRoot: true
  runAsUser: 1000

container:
  image: registry.infanasotku.com:5501/netku/netku-proxy
  tag: latest

config:
  POSTGRES__DB_NAME: netku
  REDIS__DB: "0"
  REDIS__PORT: "6381"
  RABBIT_PROXY_VHOST: "/proxy"
  RABBIT__USERNAME: "proxy"
