name: Deploy to test
on:
  push:
    branches:
      - test

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    environment: build

    steps:
      - uses: actions/checkout@v4

      - name: Build for Test
        uses: ./.github/actions/build
        with:
          environment: test
          registry_url: ${{ vars.REGISTRY_URL }}
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}

  api:
    name: Deploy api
    runs-on: ubuntu-latest
    needs: [build]
    environment: deploy

    steps:
      - uses: actions/checkout@v4

      - name: Deploy api to Test
        uses: ./.github/actions/deploy
        with:
          service: api
          environment: test
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_port: ${{ secrets.SSH_PORT }}
          server_ip: ${{ secrets.SERVER_IP }}
          project_dir: ${{ secrets.PROJECT_DIR }}
