name: Deploy to test
on:
  push:
    branches:
      - test

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    environment: build

    steps:
      - uses: actions/checkout@v4

      - name: Build for Test
        uses: ./.github/actions/build
        with:
          environment: test
          registry_url: ${{ vars.REGISTRY_URL }}
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}

  migrate:
    name: Migrate
    runs-on: [self-hosted, helmfile]
    needs: [build]
    environment: migrate

    steps:
      - uses: actions/checkout@v4

      - name: Run migrations on Test
        uses: ./.github/actions/deploy
        with:
          service: migration
          environment: test

  api:
    name: Deploy api
    runs-on: [self-hosted, helmfile]
    needs: [build, migrate]
    if: >
      always() &&
      needs.build.result == 'success' &&
      (
        needs.migrate.result == 'success' ||
        needs.migrate.result == 'skipped' ||
        needs.migrate.result == 'cancelled'
      )
    environment: api
    steps:
      - uses: actions/checkout@v4

      - name: Deploy api to Test
        uses: ./.github/actions/deploy
        with:
          service: api
          environment: test

  events:
    name: Deploy events
    runs-on: [self-hosted, helmfile]
    needs: [build, migrate]
    if: >
      always() &&
      needs.build.result == 'success' &&
      (
        needs.migrate.result == 'success' ||
        needs.migrate.result == 'skipped' ||
        needs.migrate.result == 'cancelled'
      )
    environment: events
    steps:
      - uses: actions/checkout@v4

      - name: Deploy events to Test
        uses: ./.github/actions/deploy
        with:
          service: events
          environment: test

  outbox:
    name: Deploy outbox
    runs-on: [self-hosted, helmfile]
    needs: [build, migrate]
    if: >
      always() &&
      needs.build.result == 'success' &&
      (
        needs.migrate.result == 'success' ||
        needs.migrate.result == 'skipped' ||
        needs.migrate.result == 'cancelled'
      )
    environment: outbox
    steps:
      - uses: actions/checkout@v4

      - name: Deploy outbox to Test
        uses: ./.github/actions/deploy
        with:
          service: outbox
          environment: test
