name: Deploy to test
on:
  push:
    branches:
      - test

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    environment: build

    steps:
      - uses: actions/checkout@v4

      - name: Build for Test
        uses: ./.github/actions/build
        with:
          environment: test
          registry_url: ${{ vars.REGISTRY_URL }}
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}

  prepare:
    name: Prepare repository
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: Prepare repo on server
        run: |
          ssh -p ${{ secrets.SSH_PORT }} root@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            cd ${{ secrets.PROJECT_DIR }}

            git restore .
            git fetch
            git checkout test
            git pull
          EOF
  api:
    name: Deploy api
    runs-on: ubuntu-latest
    needs: [prepare]
    environment: deploy

    steps:
      - uses: actions/checkout@v4

      - name: Deploy api to Test
        uses: ./.github/actions/deploy
        with:
          service: api
          environment: test
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_port: ${{ secrets.SSH_PORT }}
          server_ip: ${{ secrets.SERVER_IP }}
          project_dir: ${{ secrets.PROJECT_DIR }}

  events:
    name: Deploy events
    runs-on: ubuntu-latest
    needs: [prepare]
    environment: deploy

    steps:
      - uses: actions/checkout@v4

      - name: Deploy events to Test
        uses: ./.github/actions/deploy
        with:
          service: events
          environment: test
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_port: ${{ secrets.SSH_PORT }}
          server_ip: ${{ secrets.SERVER_IP }}
          project_dir: ${{ secrets.PROJECT_DIR }}

  outbox:
    name: Deploy outbox
    runs-on: ubuntu-latest
    needs: [prepare]
    environment: deploy

    steps:
      - uses: actions/checkout@v4

      - name: Deploy outbox to Test
        uses: ./.github/actions/deploy
        with:
          service: outbox
          environment: test
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_port: ${{ secrets.SSH_PORT }}
          server_ip: ${{ secrets.SERVER_IP }}
          project_dir: ${{ secrets.PROJECT_DIR }}
